### ISSUE TITLE
Wallpaper Animation Laggy/Choppy

### ISSUE THREAD

**Issue by jonasisozen** [cvzi/darkmodewallpaper#14]
the wallpaper animation (zoom in) while sliding down the slide-down menu is choppy and irritating. 
A option for disabling it would be nice.
My setup: Lg V20 Lineage Os 18 de-googled

**Comment by cvzi** [comment]
I'll try to make it smoother, add a switch to disable it and probably also disable it by default. I don't really understand the purpose of the zoom anyway.

I implemented it without testing it, because my phone does not support it. I think it is only a feature of Android 11 while my phone is still on 10. 

Thanks for the report!
